# Generated by Django 3.0.8 on 2020-07-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('location_x', models.FloatField(blank=True, db_column='location_X', null=True)),
                ('location_y', models.FloatField(blank=True, db_column='location_Y', null=True)),
            ],
            options={
                'db_table': 'data',
                'managed': False,
            },
        ),
    ]
